### ISSUE TITLE
"Click here to upload a" is displayed instead of "Click here to upload a photo" in change profile screen

### ISSUE THREAD

**Issue by Sreenisankar** [sabeenabusali/MyDesk#254]
# <h3>Precondition

Open My Desk web app in Firefox browser.
# <h3>Steps to reproduce
1. Goto change profile picture

2.Observe the profile pic upload link
# <h3>Issue

1."Click here to upload a photo" text is not proper.It is not fully displayed(Ref screenshot)
2. Unable click the link"Click here to upload a photo"
# <h3>Expected

Full text "Click here to upload a photo" should be displayed.

![upload pic link](https://cloud.githubusercontent.com/assets/12081296/7312242/b38a5662-ea65-11e4-80fa-ddab7fcc19f6.jpg)

**Comment by sijupg** [comment]
Not valid in the current implimentation.
