### ISSUE TITLE
Unable to upload image in the below mentioned scenario.

### ISSUE THREAD

**Issue by Sreenisankar** [sabeenabusali/MyDesk#255]
# <h4>Precondition

Open My Desk web app in chrome browser.
# <h4>Steps to reproduce

1.Goto change profile picture.

2.Click the profile pic upload link.

3.Select any image to upload.

4.Try to crop the uploaded image.

5.Again click the profile pic upload link and press cancel button.

6.Observe the screen.
# <h4>Issue

Unwanted crop selection and shade of uploaded image is displayed as overlapped within the page. 
# <h4>Expected

Only the uploaded image should be displayed.
# <h4>attached files

![profile pic selection](https://cloud.githubusercontent.com/assets/12081296/7312386/48f9176e-ea67-11e4-8b12-5b811e94d529.jpg)

**Comment by sijupg** [comment]
Not valid in the current implimentation
