### ISSUE TITLE
Android App: unable to dismiss keyboard after searching in my desk

### ISSUE THREAD

**Issue by biswash** [sabeenabusali/MyDesk#321]
# <h4> Steps to reproduce
1. Tap on search bar
2. search a keyword
3. Clear the keyword using backspace
4. Now cancel search button is gone and no way to dismiss the keyboad. Only way is using phone's back button
# <h4> Issue

Cancel search button is gone and no way to dismiss the keyboad. Only way is using phone's back button
# <h4> Expected results

Cancel button remains to dismiss the keyboard

**Comment by KSShamon** [comment]
you have to press back button to hide keyboard as like in whatsapp
