### ISSUE TITLE
Container Icon in web should be changed as in mobile apps

### ISSUE THREAD

**Issue by biswash** [sabeenabusali/MyDesk#79]
Container Icon in web--- ![listviewcontainericon](https://cloud.githubusercontent.com/assets/11155104/6390648/171d12fa-bdd4-11e4-9365-cb0c72f9dcbe.png)--- should be changed as in mobile apps ---![recent_fileshare_container](https://cloud.githubusercontent.com/assets/11155104/6390633/ff1450a6-bdd3-11e4-8b28-cc2a6128bc23.png)

**Comment by biswash** [comment]
There is a small alignment issue with the Icon inside the square.Need to move it a bit left to make it centralized

**Comment by jobin333** [comment]
Copy and Move list items need to change..
